{% set name = "virushostinteractionpredictor" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/virushostinteractionpredictor-{{ version }}.tar.gz
  sha256: 14023a4474a96fdbeb9c85b38e8aca7144ab780ed5900090bcd644a834c92719

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - poetry-core
    - pip
  run:
    - python >=3.9
    - biopython
    - numpy
    - pandas
    - scikit-learn

test:
  imports:
    - vhip
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/DuhaimeLab/VirusHostInteractionPredictor
  summary: 'Python tool to predict ecological virus-host infection'
  description: |
    Virus Host Interaction Predictor (VHIP) is a machine-learning model that
    predicts virus-microbe interactions (i.e., infection or non-infection) from
    genomic sequences of viruses and microbes of interest. It leverages
    virus-microbe coevolution signals that are extracted from genomic
    sequences. VHIP was trained on lab-verified virus-microbe pairs
    collected from literature and the NCBI virus database.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/DuhaimeLab/VirusHostInteractionPredictor

extra:
  recipe-maintainers:
    - GBastion
